In [4]:
from keras.layers import Dense, Dropout, LSTM, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import pandas as pd
import numpy as np

input_file = 'input.csv'

def load_data(test_split = 0.2):
    print ('Loading data...')
    df = pd.read_csv(input_file)
    df['sequence'] = df['sequence'].apply(lambda x: [int(e) for e in x.split()])
    df = df.reindex(np.random.permutation(df.index))
    print(df)
    train_size = int(len(df) * (1 - test_split))

    X_train = df['sequence'].values[:train_size]
    y_train = np.array(df['target'].values[:train_size])
    X_test = np.array(df['sequence'].values[train_size:])
    y_test = np.array(df['target'].values[train_size:])
    
    return pad_sequences(X_train), y_train, pad_sequences(X_test), y_test


def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 188, output_dim = 50, input_length = input_length))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))
    model.add(Dropout(0.5))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
    return model


X_train, y_train, X_test, y_test = load_data()

model = create_model(len(X_train[0]))

print ('Fitting model...')
hist = model.fit(X_train, y_train, batch_size=64, nb_epoch=10, validation_split = 0.1, verbose = 1)

score, acc = model.evaluate(X_test, y_test, batch_size=1)
print('Test score:', score)
print('Test accuracy:', acc)

Loading data...
    sequence  target
8  [2, 1, 3]       0
1  [2, 3, 1]       0
2  [2, 3, 4]       1
5  [3, 2, 1]       0
7  [2, 2, 3]       1
6  [1, 2, 4]       1
0  [1, 2, 3]       1
3  [4, 2, 1]       0
4  [4, 3, 1]       0
[list([2, 1, 3]) list([2, 3, 1]) list([2, 3, 4]) list([3, 2, 1])
 list([2, 2, 3]) list([1, 2, 4]) list([1, 2, 3])]
[[2 1 3]
 [2 3 1]
 [2 3 4]
 [3 2 1]
 [2 2 3]
 [1 2 4]
 [1 2 3]]
Creating model...


C:\Users\kamran\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", return_sequences=True, units=256, recurrent_activation="hard_sigmoid")`
C:\Users\kamran\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", units=256, recurrent_activation="hard_sigmoid")`


Compiling...
Fitting model...


C:\Users\kamran\Anaconda3\lib\site-packages\ipykernel_launcher.py:48: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 6 samples, validate on 1 samples
Epoch 1/10
6/6 [==============================] - 3s 552ms/step - loss: 0.5831 - acc: 1.0000 - val_loss: 0.8387 - val_acc: 0.0000e+00
Epoch 2/10
6/6 [==============================] - 0s 8ms/step - loss: 0.7909 - acc: 0.5000 - val_loss: 0.8219 - val_acc: 0.0000e+00
Epoch 3/10
6/6 [==============================] - 0s 9ms/step - loss: 0.7714 - acc: 0.1667 - val_loss: 0.6204 - val_acc: 1.0000
Epoch 4/10
6/6 [==============================] - 0s 8ms/step - loss: 0.7203 - acc: 0.5000 - val_loss: 0.8963 - val_acc: 0.0000e+00
Epoch 5/10
6/6 [==============================] - 0s 8ms/step - loss: 0.6800 - acc: 0.6667 - val_loss: 0.6201 - val_acc: 1.0000
Epoch 6/10
6/6 [==============================] - 0s 8ms/step - loss: 0.6271 - acc: 0.8333 - val_loss: 0.7312 - val_acc: 0.0000e+00
Epoch 7/10
6/6 [==============================] - 0s 9ms/step - loss: 0.5875 - acc: 0.8333 - val_loss: 0.5871 - val_acc: 1.0000
Epoch 8/10
6/6 [============================