In [2]:
import pandas as pd
import requests as req
import re
import json
import numpy as np
import jalali
from scipy import stats
import os

In [3]:
# directory = os.getcwd()
# for filename in os.listdir(directory):
#     if filename.endswith(".csv"):
#         file = pd.read_csv(filename)

In [6]:
zagros_train = pd.read_csv("zagros 1397-7-22.csv")

zagros_test = pd.read_csv("zagros 1397-7-23.csv")
zagros_test.head()
zagros_train.shape,zagros_test.shape
pd.concat([zagros_train,zagros_test]).shape

(3073, 28)

In [5]:
zagros_train.isna().any()

Unnamed: 0      False
time1           False
Spread          False
Mid-price       False
volume_buy1     False
price_buy1      False
price_sell1     False
volume_sell1    False
time2           False
volume_buy2     False
price_buy2      False
price_sell2     False
volume_sell2    False
time3           False
volume_buy3     False
price_buy3      False
price_sell3     False
volume_sell3    False
time4           False
volume_buy4     False
price_buy4      False
price_sell4     False
volume_sell4    False
time5           False
volume_buy5     False
price_buy5      False
price_sell5     False
volume_sell5    False
dtype: bool

In [6]:
zagros_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 28 columns):
Unnamed: 0      1645 non-null int64
time1           1645 non-null object
Spread          1645 non-null int64
Mid-price       1645 non-null int64
volume_buy1     1645 non-null int64
price_buy1      1645 non-null int64
price_sell1     1645 non-null int64
volume_sell1    1645 non-null int64
time2           1645 non-null object
volume_buy2     1645 non-null int64
price_buy2      1645 non-null int64
price_sell2     1645 non-null int64
volume_sell2    1645 non-null int64
time3           1645 non-null object
volume_buy3     1645 non-null int64
price_buy3      1645 non-null int64
price_sell3     1645 non-null int64
volume_sell3    1645 non-null int64
time4           1645 non-null object
volume_buy4     1645 non-null int64
price_buy4      1645 non-null int64
price_sell4     1645 non-null int64
volume_sell4    1645 non-null int64
time5           1645 non-null object
volume_buy5     1645 non

In [7]:
def set_label(k,nparray):
    lst = []
    for i in range(0,nparray.shape[0]-k):
        eq = 0
        for j in range(i+1,i+k+1):
            eq = eq + nparray[j]-nparray[i]
        numerator = eq/k
        fraction = numerator / nparray[i]
        lst.append(fraction)
    lst = lst+[lst[-1]]*k
    len(lst)
    label = np.array([i for i in lst],dtype=np.float)
    return label

In [8]:
Spread = zagros_train["Spread"].values
Spread = stats.zscore(Spread)

mid_price = zagros_train["Mid-price"].values
target = set_label(10,mid_price)
target_zscore = stats.zscore(target)
mid_price = stats.zscore(mid_price)

volume_buy1 = zagros_train["volume_buy1"].values
volume_buy1 = stats.zscore(volume_buy1)

price_buy1 = zagros_train["price_buy1"].values
price_buy1 = stats.zscore(price_buy1)

price_sell1 = zagros_train["price_sell1"].values
price_sell1 = stats.zscore(price_sell1)

volume_sell1 = zagros_train["volume_sell1"].values
volume_sell1 = stats.zscore(volume_sell1)
###############
volume_buy2 = zagros_train["volume_buy2"].values
volume_buy2 = stats.zscore(volume_buy2)

price_buy2 = zagros_train["price_buy2"].values
price_buy2 = stats.zscore(price_buy2)

price_sell2 = zagros_train["price_sell2"].values
price_sell2 = stats.zscore(price_sell2)

volume_sell2 = zagros_train["volume_sell2"].values
volume_sell2 = stats.zscore(volume_sell2)
###############
volume_buy3 = zagros_train["volume_buy3"].values
volume_buy3 = stats.zscore(volume_buy3)

price_buy3 = zagros_train["price_buy3"].values
price_buy3 = stats.zscore(price_buy3)

price_sell3 = zagros_train["price_sell3"].values
price_sell3 = stats.zscore(price_sell3)

volume_sell3 = zagros_train["volume_sell3"].values
volume_sell3 = stats.zscore(volume_sell3)
##############
volume_buy4 = zagros_train["volume_buy4"].values
volume_buy4 = stats.zscore(volume_buy4)

price_buy4 = zagros_train["price_buy4"].values
price_buy4 = stats.zscore(price_buy4)

price_sell4 = zagros_train["price_sell4"].values
price_sell4 = stats.zscore(price_sell4)

volume_sell4 = zagros_train["volume_sell4"].values
volume_sell4 = stats.zscore(volume_sell4)
###############
volume_buy5 = zagros_train["volume_buy5"].values
volume_buy5 = stats.zscore(volume_buy5)

price_buy5 = zagros_train["price_buy5"].values
price_buy5 = stats.zscore(price_buy5)

price_sell5 = zagros_train["price_sell5"].values
price_sell5 = stats.zscore(price_sell5)

volume_sell5 = zagros_train["volume_sell5"].values
volume_sell5 = stats.zscore(volume_sell5)


In [9]:
Spreadtest = zagros_test["Spread"].values
Spreadtest = stats.zscore(Spreadtest)

mid_pricetest = zagros_test["Mid-price"].values
targettest = set_label(10,mid_pricetest)
target_zscoretest = stats.zscore(targettest)
mid_pricetest = stats.zscore(mid_pricetest)

volume_buy1test = zagros_test["volume_buy1"].values
volume_buy1test = stats.zscore(volume_buy1test)

price_buy1test = zagros_test["price_buy1"].values
price_buy1test = stats.zscore(price_buy1test)

price_sell1test = zagros_test["price_sell1"].values
price_sell1test = stats.zscore(price_sell1test)

volume_sell1test = zagros_test["volume_sell1"].values
volume_sell1test = stats.zscore(volume_sell1test)
###############
volume_buy2test = zagros_test["volume_buy2"].values
volume_buy2test = stats.zscore(volume_buy2test)

price_buy2test = zagros_test["price_buy2"].values
price_buy2test = stats.zscore(price_buy2test)

price_sell2test = zagros_test["price_sell2"].values
price_sell2tset = stats.zscore(price_sell2test)

volume_sell2test = zagros_test["volume_sell2"].values
volume_sell2test = stats.zscore(volume_sell2test)
###############
volume_buy3test = zagros_test["volume_buy3"].values
volume_buy3test = stats.zscore(volume_buy3test)

price_buy3test = zagros_test["price_buy3"].values
price_buy3test = stats.zscore(price_buy3test)

price_sell3test = zagros_test["price_sell3"].values
price_sell3test = stats.zscore(price_sell3test)

volume_sell3test = zagros_test["volume_sell3"].values
volume_sell3test = stats.zscore(volume_sell3test)
##############
volume_buy4test = zagros_test["volume_buy4"].values
volume_buy4test = stats.zscore(volume_buy4test)

price_buy4test = zagros_test["price_buy4"].values
price_buy4test = stats.zscore(price_buy4test)

price_sell4test = zagros_test["price_sell4"].values
price_sell4test = stats.zscore(price_sell4test)

volume_sell4test = zagros_test["volume_sell4"].values
volume_sell4test = stats.zscore(volume_sell4test)
###############
volume_buy5test = zagros_test["volume_buy5"].values
volume_buy5test = stats.zscore(volume_buy5test)

price_buy5test = zagros_test["price_buy5"].values
price_buy5test = stats.zscore(price_buy5test)

price_sell5test = zagros_test["price_sell5"].values
price_sell5test = stats.zscore(price_sell5test)

volume_sell5test = zagros_test["volume_sell5"].values
volume_sell5test = stats.zscore(volume_sell5test)
targettest.shape,volume_sell5test.shape

((1428,), (1428,))

In [10]:
upward = 0.002
low_stationary = -0.00199
high_stationary = 0.00199
downward = -0.002

# if target[0] >= upward:
#     nplabel = np.array([[1,-1,-1]])
# elif low_stationary < target[0] < high_stationary:
#     nplabel = np.array([[-1,1,-1]])
# elif target[0] <= downward:
#     nplabel = np.array([[-1,-1,1]])
    
# nplabel = np.array([[0,0,0]])

# for item in target:
#     if item >= upward:
#         nplabel = np.append(nplabel,[[1,-1,-1]],axis=0)
#     elif low_stationary < item < high_stationary:
#         nplabel = np.append(nplabel,[[-1,1,-1]],axis=0)
#     elif item <= downward:
#         nplabel = np.append(nplabel,[[-1,-1,1]],axis=0)
lst=[]
for item in target:
    if item >= upward:
        lst.append(1)
    elif item <= downward:
        lst.append(5)
    else:
        lst.append(3)
    

In [11]:
X = np.array([Spread,
              volume_buy1,price_buy1,price_sell1,volume_sell1,
                               volume_buy2,price_buy2,price_sell2,volume_sell2,
                               volume_buy3,price_buy3,price_sell3,volume_sell3,
                               volume_buy4,price_buy4,price_sell4,volume_sell4,
                               volume_buy5,price_buy5,price_sell5,volume_sell5,
             ])

nplabel = np.array([i for i in lst],dtype=int)
Y_train = np.expand_dims(nplabel,axis=1)
X_train = np.transpose(X)


In [12]:
X_test = np.array([Spreadtest,
              volume_buy1test,price_buy1test,price_sell1test,volume_sell1test,
              volume_buy2test,price_buy2test,price_sell2test,volume_sell2test,
              volume_buy3test,price_buy3test,price_sell3test,volume_sell3test,
              volume_buy4test,price_buy4test,price_sell4test,volume_sell4test,
              volume_buy5test,price_buy5test,price_sell5test,volume_sell5test,
             ])
lsttest=[]
for item in targettest:
    if item >= upward:
        lsttest.append(1)
    elif item <= downward:
        lsttest.append(5)
    else:
        lsttest.append(3)
    
nplabeltest = np.array([i for i in lsttest],dtype=int)
Y_test = np.expand_dims(nplabeltest,axis=1)
X_test = np.transpose(X_test)
Y_test.shape,X_test.shape,X_train.shape,Y_train.shape

((1428, 1), (1428, 21), (1645, 21), (1645, 1))

In [13]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn import svm
# X_train, X_test, Y_train, Y_test = train_test_split(Xt,T,test_size=0.2,random_state=10)
# ridge_train_pred = []
# ridge_test_pred = []

#training
ridge_reg = svm.SVC(gamma='scale', decision_function_shape='ovo')
ridge_reg.fit(X_train,Y_train)
#prediction
pred_train = ridge_reg.predict(X_train)
pred_test = ridge_reg.predict(X_test)

# pred_train = np.round(pred_train,decimals=0).astype(int)
# pred_test = np.round(pred_test,decimals=0).astype(int)


# for alpha in np.arange(0,200,1):
#     #training
#     ridge_reg = Ridge(alpha=alpha)
#     ridge_reg.fit(X_train,y_train)
#     #prediction
#     ridge_train_pred.append(ridge_reg.predict(X_train))
#     ridge_train_pred.append(ridge_reg.predict(X_test))

#convert pred_train to 1,3,5
pred_train = pred_train//2*2+1
pred_test = pred_test//2*2+1

C:\Users\kamran\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

Y_train.shape,pred_train.shape
print("accuracy")
print(accuracy_score(Y_train,pred_train))
print(accuracy_score(Y_test,pred_test))
print("precision")
print(precision_score(Y_train,pred_train,average='weighted'))
print(precision_score(Y_test,pred_test,average='weighted'))
print("recall")
print(recall_score(Y_train,pred_train,average='weighted'))
print(recall_score(Y_test,pred_test,average='weighted'))
print("f1-score")
print(f1_score(Y_train,pred_train,average='weighted'))
print(f1_score(Y_test,pred_test,average='weighted'))

C:\Users\kamran\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


accuracy
0.9252279635258359
0.8487394957983193
precision
0.9288992607002452
0.7203587317279853
recall
0.9252279635258359
0.8487394957983193
f1-score
0.9100620149439077
0.7792971734148204


C:\Users\kamran\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [81]:
X_train.shape

(1718, 22)

In [24]:
np.append(a,[[1,1,1]],axis=0)

ValueError: all the input arrays must have same number of dimensions

In [154]:
a = np.array([[1,1,1],[1.,1.,-1.]])
b = np.round(a,decimals=0).astype(int)

In [159]:
accuracy_score(Y_train[0],pred_train[0])

0.3333333333333333

In [130]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [157]:
Y_train[]

array([ 1, -1, -1])

In [158]:
pred_train[0]

array([-1,  1, -1])

In [160]:
lst=[]
lst.append(1)

In [161]:
lst

[1]

In [164]:
T

array([5, 3, 3, ..., 3, 3, 3])

In [55]:
a = np.array([[0.3,1.7,2.9],[1.9,2.1,4.2]])
b = np.round(a,decimals=1).astype(int)

In [56]:
a//2*2+1

array([[1., 1., 3.],
       [1., 3., 5.]])